name: Issue opened

on:
  issues:
    types: [opened]

jobs:
  assign:
    name: Assign issues to project
    runs-on: ubuntu-latest
    steps:
      - name: Create Project Card Action
        uses: technote-space/create-project-card-action@v1.0.3
        with:
          PROJECT: Demo Backlog
          COLUMN: 🆕 New
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}